[server]
address = "127.0.0.1"
port = 5000
threads = 4

[s3]
host = "localhost"
port = "9000"
bucket = "audio-files"
access_key = "minioadmin"
secret_key = "minioadmin123"
region = "us-east-1"
service ="s3"

[janus]
address = "10.0.0.24"
port_start = "10000"
port_end ="10200"
