

services:

  hermes_server:
    build: .
    command: tail -f /dev/null
    network_mode: "host"
    volumes:
      - .:/app
      - hermes_build_cache:/app/build
    depends_on:
      - minio
    privileged: true
    environment:
      - S3_HOST=localhost
      - S3_PORT=9000


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  janus:
    image: canyan/janus-gateway:latest
    container_name: janus_gateway
    restart: unless-stopped
    ports:
      - "8088:8088"  # HTTP API
      - "8188:8188"  # WebSocket API
      - "7088:7088"  # Admin API
      - "10000-10200:10000-10200/udp" # RTP Media Ports (MUST match config)
      - "5002:5002/udp"
    volumes:
      # Mount your configured local folder into the container
      - ./janus_conf:/usr/local/etc/janus
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]

  demo_viewer:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      # Maps your local 'demos' folder to the container's web root
      - ./demos:/usr/share/nginx/html
volumes:
  hermes_build_cache:
  minio_data:
